name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-x86:
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Release|x86
        run: >
          msbuild l4d2vr.sln
          /p:Configuration=Release /p:Platform=x86
          /t:Rebuild
          /consoleloggerparameters:ErrorsOnly
        working-directory: ${{ github.workspace }}

      - name: Upload artifact (x86)
        uses: actions/upload-artifact@v4
        with:
          name: Portal2VR_x86
          path: Release/d3d9.dll

  build-x64:
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Release|x64
        run: >
          msbuild l4d2vr.sln
          /p:Configuration=Release /p:Platform=x64
          /t:Rebuild
          /consoleloggerparameters:ErrorsOnly
        working-directory: ${{ github.workspace }}

      - name: Upload artifact (x64)
        uses: actions/upload-artifact@v4
        with:
          name: Portal2VR_x64
          path: x64/Release/d3d9.dll
